#!/bin/bash
set -eu
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

slicot_sources_cmake_file="cmake/slicot_sources.cmake"
cat <<EOF > "$slicot_sources_cmake_file"
# This file was automatically generated by tools/generate_cmake_files.sh
set(SLICOT_SOURCES
EOF

find src/ -name *.f|sed 's/src\//  \${CMAKE_SOURCE_DIR}\/src\//g' >> "$slicot_sources_cmake_file"
echo ")" >> "$slicot_sources_cmake_file"
